<a href="https://colab.research.google.com/github/JerryK97/dl12/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ch02_numpy.ipynb
- numpy 공부

In [1]:
# chap02 - numpy
import numpy as np

In [2]:

# ndarray
a = np.array([1, 2, 3])

a, a[0], type(a)

(array([1, 2, 3]), 1, numpy.ndarray)

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b)
b[0][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [5]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

print(a.shape)     #모양
print(a.ndim)      #차원
print(a.dtype)     #데이터 타입
print(a.itemsize)  #데이터 사이즈
a.size             #원소 갯수

(3, 3)
2
int64
8


9

In [8]:
#영행렬
np.zeros((3, 4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#정방행렬
np.ones( (3, 4), dtype=np.int32 )

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
#단위행렬
np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
x = np.ones(5, dtype=np.int64)

x

array([1, 1, 1, 1, 1])

In [14]:
print(np.arange(5))

print(np.arange(1, 6))

print(np.arange(1, 10, 2))

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5 7 9]


In [15]:
np.linspace(0, 10, 101)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [17]:
# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])

x, y

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [25]:
np.concatenate((x, y), axis=0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
np.concatenate((x, y), axis=1)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
np.vstack((x, y))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
# reshape
a = np.arange(12)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [28]:
print(a.reshape(3, 4))

print(a.reshape(6, -1))

print(a.reshape(-1, 6))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [35]:
array = np.arange(30).reshape(-1, 10)

array, array.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [36]:
arr1, arr2 = np.split(array, [3], axis=1)

print(arr1)

print(arr2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]]


In [37]:
# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [38]:
a1 = a[np.newaxis, :]

a1, a1.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [39]:
a2 = a[:, np.newaxis]

a2, a2.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]), (6, 1))

### indexing & slicing

In [40]:
ages = np.array([18, 19, 25, 30, 28])

ages[1:3], ages[:2]

(array([19, 25]), array([18, 19]))

In [41]:
y = ages > 20

y

array([False, False,  True,  True,  True])

In [42]:
#조건을 만족하는 데이터 선택
ages[ ages > 20 ]

array([25, 30, 28])

In [44]:
# 인덱싱
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

a

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [45]:
# 슬라이싱
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

###  numpy 연산


#### 브로드케스팅 (broadcasting)

In [47]:
miles = np.array([1, 2, 3])

result = miles * 1.6

result

array([1.6, 3.2, 4.8])

#### elementwise 연산

In [46]:
#덧셈
arr1 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr2 = np.array([[1, 1],
                 [1, 1],
                 [1, 1]])

result = arr1 + arr2

result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [48]:
#곱셈
arr1 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr2 = np.array([[2, 2],
                 [2, 2],
                 [2, 2]])

result = arr1 * arr2

result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

#### vectorwise 연산

In [49]:
#행렬 곱셈
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr2 = np.array([[2, 2],
                 [2, 2],
                 [2, 2]])

result = arr1 @ arr2

result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [51]:
arr1.dot(arr2)

array([[12, 12],
       [30, 30],
       [48, 48]])

#### 추가 함수들

In [52]:
A = np.array([0, 1, 2, 3])

10 * np.sin(A)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [53]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(), a.min(), a.max()

(45, 1, 9)

In [54]:
#최소 최대값의 인덱스 값 호출 함수
a.argmin(), a.argmax() #2차원 배열이면 flatten해서 인덱스 값을 준다

(0, 8)

In [58]:
scores = np.array([[99, 93, 60],
                   [98, 82, 93],
                   [93, 65, 81],
                   [78, 82, 81]])    
print(scores.mean())

print(scores.mean(axis=0)) #열

scores.mean(axis=1)        #행

83.75
[92.   80.5  78.75]


array([84.        , 91.        , 79.66666667, 80.33333333])

## 무작위 수 배열

In [67]:
# random numbers
np.random.seed(100)

In [68]:
print(np.random.rand(5))
np.random.rand(5)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]


array([0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [62]:
np.random.rand(5, 3)

array([[0.43170418, 0.94002982, 0.81764938],
       [0.33611195, 0.17541045, 0.37283205],
       [0.00568851, 0.25242635, 0.79566251],
       [0.01525497, 0.59884338, 0.60380454],
       [0.10514769, 0.38194344, 0.03647606]])

In [63]:
np.random.randn(5)

array([1.56717879, 0.49702472, 1.15587233, 1.83861168, 1.53572662])

In [64]:
np.random.randn(5, 4)

array([[ 0.25499773, -0.84415725, -0.98294346, -0.30609783],
       [ 0.83850061, -1.69084816,  1.15117366, -1.02933685],
       [-0.51099219, -2.36027053,  0.10359513,  1.73881773],
       [ 1.24187584,  0.13241276,  0.57779396, -1.57590571],
       [-1.29279424, -0.65991979, -0.87400478, -0.68955061]])

### [DIY]
- 컬러 이미지 100장을 무작위로 생성
- 이미지 크기는 28 x 28

In [69]:
image100 = np.random.randn(100, 28, 28, 3)
image100.shape

(100, 28, 28, 3)

In [72]:
m, sigma = 10, 2  #평균, 표준편차

m + sigma*np.random.randn(5)

array([10.2881178 , 16.42429223,  8.80377882,  6.92732875, 11.28182048])

In [73]:
mu, sigma = 0, 2

np.random.normal(mu, sigma, 5) #평균표준편차

array([-0.13966742,  4.12578837, -1.87399273,  0.07239857, -1.360551  ])

### np.unique()

In [78]:
#중복 제거
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)

unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
#젤 처음 나온 값의 인덱스 값 호출
uv, ui = np.unique(a, return_index = True)
uv, ui

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [81]:
#값들의 중복된 갯수
uv, uc = np.unique(a, return_counts = True)
uv, uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [82]:
# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

[[1 3 5]
 [2 4 6]]


In [83]:
# 평탄화
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## pandas / matplotlib

In [ ]:
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 